[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

[rpc_endpoints]
polygon = "https://polygon-rpc.com/"
polygon_amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }
