[build]
  command = "cd frontend && npm run build"
  publish = "frontend/out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix ./frontend"